### ISSUE TITLE
opentelemetry-tasks-runner: exporters dependencies

### ISSUE THREAD

**Issue by Djiit** [gibsonjoshua55/nxpansion#5]
Hey :wave: 

When using the `otlp-http` exporter, I also have to install the `grpc` one for this package to work.
I can think of a few workarounds:
- ship these 2 dependencies with the package
- lazy load/import them instead of requiring them at the top of a file

Cheers

**Comment by gibsonjoshua55** [comment]
I love the idea of lazy loading them!

With [`peerDependenciesMeta`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependenciesmeta) we should be able to mark those grpc/exporter dependencies as optional peer dependencies.
